### ISSUE TITLE
Error on "npm install"

### ISSUE THREAD

**Issue by McPo** [bytheway/electron-sqlite3#2]
````
mcp-air:electron-sqlite3 mcp$ npm install
npm WARN deprecated electron-packager@5.2.1: Critical security bug fixed in v7.0.0 - read more at https://github.com/electron-userland/electron-packager/issues/333
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> sqlite3@3.1.1 install /Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3090100/sqlite3.o
Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c:9704:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../src/database.cc:143:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:227:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:505:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:605:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
4 warnings and 4 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/lib/binding/node-v48-darwin-x64"
gyp ERR! cwd /Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/lib/binding/node-v48-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 15.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/6.2.1/bin/node" "/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.14
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp build --fallback-to-build --module=/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/lib/binding/node-v48-darwin-x64' (1)
electron-sqlite3@1.0.0 /Users/mcp/Downloads/electron-sqlite3
├─┬ electron-packager@5.2.1
│ ├─┬ asar@0.8.3
│ │ ├── chromium-pickle-js@0.1.0
│ │ ├── commander@2.3.0
│ │ ├── cuint@0.1.5
│ │ ├─┬ glob@5.0.15
│ │ │ ├─┬ inflight@1.0.5
│ │ │ │ └── wrappy@1.0.2
│ │ │ ├── inherits@2.0.1
│ │ │ ├── once@1.3.3
│ │ │ └── path-is-absolute@1.0.0
│ │ ├─┬ minimatch@2.0.4
│ │ │ └─┬ brace-expansion@1.1.5
│ │ │   ├── balanced-match@0.4.1
│ │ │   └── concat-map@0.0.1
│ │ └─┬ mksnapshot@0.1.0
│ │   ├─┬ decompress-zip@0.1.0
│ │   │ ├─┬ binary@0.3.0
│ │   │ │ ├── buffers@0.1.1
│ │   │ │ └─┬ chainsaw@0.1.0
│ │   │ │   └── traverse@0.3.9
│ │   │ ├── graceful-fs@3.0.8
│ │   │ ├── mkpath@0.1.0
│ │   │ ├─┬ nopt@3.0.6
│ │   │ │ └── abbrev@1.0.9
│ │   │ ├── q@1.4.1
│ │   │ ├─┬ readable-stream@1.1.14
│ │   │ │ └── isarray@0.0.1
│ │   │ └─┬ touch@0.0.3
│ │   │   └── nopt@1.0.10
│ │   ├─┬ fs-extra@0.18.2
│ │   │ └── jsonfile@2.3.1
│ │   └─┬ request@2.55.0
│ │     ├── aws-sign2@0.5.0
│ │     ├─┬ bl@0.9.5
│ │     │ └── readable-stream@1.0.34
│ │     ├── caseless@0.9.0
│ │     ├─┬ combined-stream@0.0.7
│ │     │ └── delayed-stream@0.0.5
│ │     ├── forever-agent@0.6.1
│ │     ├─┬ form-data@0.2.0
│ │     │ └── async@0.9.2
│ │     ├─┬ har-validator@1.8.0
│ │     │ ├── bluebird@2.10.2
│ │     │ ├─┬ chalk@1.1.3
│ │     │ │ ├── ansi-styles@2.2.1
│ │     │ │ ├── escape-string-regexp@1.0.5
│ │     │ │ ├─┬ has-ansi@2.0.0
│ │     │ │ │ └── ansi-regex@2.0.0
│ │     │ │ ├── strip-ansi@3.0.1
│ │     │ │ └── supports-color@2.0.0
│ │     │ ├─┬ commander@2.9.0
│ │     │ │ └── graceful-readlink@1.0.1
│ │     │ └─┬ is-my-json-valid@2.13.1
│ │     │   ├── generate-function@2.0.0
│ │     │   ├─┬ generate-object-property@1.2.0
│ │     │   │ └── is-property@1.0.2
│ │     │   ├── jsonpointer@2.0.0
│ │     │   └── xtend@4.0.1
│ │     ├─┬ hawk@2.3.1
│ │     │ ├── boom@2.10.1
│ │     │ ├── cryptiles@2.0.5
│ │     │ ├── hoek@2.16.3
│ │     │ └── sntp@1.0.9
│ │     ├─┬ http-signature@0.10.1
│ │     │ ├── asn1@0.1.11
│ │     │ ├── assert-plus@0.1.5
│ │     │ └── ctype@0.5.3
│ │     ├── isstream@0.1.2
│ │     ├── json-stringify-safe@5.0.1
│ │     ├─┬ mime-types@2.0.14
│ │     │ └── mime-db@1.12.0
│ │     ├── node-uuid@1.4.7
│ │     ├── oauth-sign@0.6.0
│ │     ├── qs@2.4.2
│ │     ├── stringstream@0.0.5
│ │     ├── tough-cookie@2.2.2
│ │     └── tunnel-agent@0.4.3
│ ├─┬ electron-download@1.4.1
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── home-path@1.0.3
│ │ ├─┬ nugget@1.6.2
│ │ │ ├─┬ pretty-bytes@1.0.4
│ │ │ │ ├── get-stdin@4.0.1
│ │ │ │ └─┬ meow@3.7.0
│ │ │ │   ├─┬ camelcase-keys@2.1.0
│ │ │ │   │ └── camelcase@2.1.1
│ │ │ │   ├── decamelize@1.2.0
│ │ │ │   ├─┬ loud-rejection@1.4.1
│ │ │ │   │ ├─┬ currently-unhandled@0.4.1
│ │ │ │   │ │ └── array-find-index@1.0.1
│ │ │ │   │ └── signal-exit@2.1.2
│ │ │ │   ├── map-obj@1.0.1
│ │ │ │   ├─┬ normalize-package-data@2.3.5
│ │ │ │   │ ├── hosted-git-info@2.1.5
│ │ │ │   │ ├─┬ is-builtin-module@1.0.0
│ │ │ │   │ │ └── builtin-modules@1.1.1
│ │ │ │   │ ├── semver@5.1.0
│ │ │ │   │ └─┬ validate-npm-package-license@3.0.1
│ │ │ │   │   ├─┬ spdx-correct@1.0.2
│ │ │ │   │   │ └── spdx-license-ids@1.2.1
│ │ │ │   │   └─┬ spdx-expression-parse@1.0.2
│ │ │ │   │     └── spdx-exceptions@1.0.4
│ │ │ │   ├── object-assign@4.1.0
│ │ │ │   ├─┬ read-pkg-up@1.0.1
│ │ │ │   │ ├─┬ find-up@1.1.2
│ │ │ │   │ │ ├── path-exists@2.1.0
│ │ │ │   │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │   │ │   └── pinkie@2.0.4
│ │ │ │   │ └─┬ read-pkg@1.1.0
│ │ │ │   │   ├─┬ load-json-file@1.1.0
│ │ │ │   │   │ ├── graceful-fs@4.1.4
│ │ │ │   │   │ ├─┬ parse-json@2.2.0
│ │ │ │   │   │ │ └─┬ error-ex@1.3.0
│ │ │ │   │   │ │   └── is-arrayish@0.2.1
│ │ │ │   │   │ ├── pify@2.3.0
│ │ │ │   │   │ └─┬ strip-bom@2.0.0
│ │ │ │   │   │   └── is-utf8@0.2.1
│ │ │ │   │   └─┬ path-type@1.1.0
│ │ │ │   │     └── graceful-fs@4.1.4
│ │ │ │   ├─┬ redent@1.0.0
│ │ │ │   │ ├─┬ indent-string@2.1.0
│ │ │ │   │ │ └─┬ repeating@2.0.1
│ │ │ │   │ │   └─┬ is-finite@1.0.1
│ │ │ │   │ │     └── number-is-nan@1.0.0
│ │ │ │   │ └── strip-indent@1.0.1
│ │ │ │   └── trim-newlines@1.0.0
│ │ │ ├─┬ progress-stream@1.2.0
│ │ │ │ ├── speedometer@0.1.4
│ │ │ │ └─┬ through2@0.2.3
│ │ │ │   └─┬ xtend@2.1.2
│ │ │ │     └── object-keys@0.4.0
│ │ │ ├── single-line-log@0.4.1
│ │ │ └── throttleit@0.0.2
│ │ ├── path-exists@1.0.0
│ │ └─┬ rc@1.1.6
│ │   ├── deep-extend@0.4.1
│ │   ├── ini@1.3.4
│ │   └── strip-json-comments@1.0.4
│ ├─┬ extract-zip@1.5.0
│ │ ├─┬ concat-stream@1.5.0
│ │ │ ├─┬ readable-stream@2.0.6
│ │ │ │ ├── core-util-is@1.0.2
│ │ │ │ ├── isarray@1.0.0
│ │ │ │ ├── process-nextick-args@1.0.7
│ │ │ │ └── string_decoder@0.10.31
│ │ │ └── typedarray@0.0.6
│ │ ├── debug@0.7.4
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ └─┬ yauzl@2.4.1
│ │   └─┬ fd-slicer@1.0.1
│ │     └── pend@1.2.0
│ ├─┬ get-package-info@0.0.2
│ │ ├── bluebird@3.4.0
│ │ └─┬ lodash.get@4.3.0
│ │   └─┬ lodash._stringtopath@4.8.0
│ │     └── lodash._basetostring@4.12.0
│ ├── minimist@1.2.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ mv@2.1.1
│ │ └─┬ rimraf@2.4.5
│ │   └── glob@6.0.4
│ ├── ncp@2.0.0
│ ├─┬ plist@1.2.0
│ │ ├── base64-js@0.0.8
│ │ ├── util-deprecate@1.0.2
│ │ ├─┬ xmlbuilder@4.0.0
│ │ │ └── lodash@3.10.1
│ │ └── xmldom@0.1.22
│ ├── rcedit@0.3.0
│ ├── resolve@1.1.7
│ ├─┬ rimraf@2.5.2
│ │ └── glob@7.0.3
│ └── run-series@1.1.4
├─┬ electron-prebuilt@0.36.12
│ └── electron-download@2.1.2
└── jquery@2.2.4

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mcp/Downloads/electron-sqlite3/npm-debug.log
````

And the last portion of npm-debug.log

````
19915 info lifecycle electron-packager@5.2.1~install: electron-packager@5.2.1
19916 silly lifecycle electron-packager@5.2.1~install: no script for install, continuing
19917 silly install jquery@2.2.4 /Users/mcp/Downloads/electron-sqlite3/node_modules/.staging/jquery-e7d2722a
19918 info lifecycle jquery@2.2.4~install: jquery@2.2.4
19919 silly lifecycle jquery@2.2.4~install: no script for install, continuing
19920 silly install sqlite3@3.1.1 /Users/mcp/Downloads/electron-sqlite3/node_modules/.staging/sqlite3-01cfd4a7
19921 info lifecycle sqlite3@3.1.1~install: sqlite3@3.1.1
19922 verbose lifecycle sqlite3@3.1.1~install: unsafe-perm in lifecycle true
19923 verbose lifecycle sqlite3@3.1.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3/node_modules/.bin:/Users/mcp/Downloads/electron-sqlite3/node_modules/.bin:/usr/local/Cellar/node/6.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mcp/Library/Android/sdk/tools:/Users/mcp/Library/Android/sdk/platform-tools:/Users/mcp/Scripts
19924 verbose lifecycle sqlite3@3.1.1~install: CWD: /Users/mcp/Downloads/electron-sqlite3/node_modules/sqlite3
19925 silly lifecycle sqlite3@3.1.1~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
19926 silly lifecycle sqlite3@3.1.1~install: Returned: code: 1  signal: null
19927 info lifecycle sqlite3@3.1.1~install: Failed to exec install script
19928 verbose unlock done using /Users/mcp/.npm/_locks/staging-c27ff3864f5ff53e.lock for /Users/mcp/Downloads/electron-sqlite3/node_modules/.staging
19929 silly rollbackFailedOptional Starting
19930 silly rollbackFailedOptional Finishing
19931 silly runTopLevelLifecycles Starting
19932 silly runTopLevelLifecycles Finishing
19933 silly install printInstalled
19934 verbose stack Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
19934 verbose stack Exit status 1
19934 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
19934 verbose stack     at emitTwo (events.js:106:13)
19934 verbose stack     at EventEmitter.emit (events.js:191:7)
19934 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
19934 verbose stack     at emitTwo (events.js:106:13)
19934 verbose stack     at ChildProcess.emit (events.js:191:7)
19934 verbose stack     at maybeClose (internal/child_process.js:852:16)
19934 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
19935 verbose pkgid sqlite3@3.1.1
19936 verbose cwd /Users/mcp/Downloads/electron-sqlite3
19937 error Darwin 15.5.0
19938 error argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
19939 error node v6.2.1
19940 error npm  v3.9.3
19941 error code ELIFECYCLE
19942 error sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
19942 error Exit status 1
19943 error Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
19943 error Make sure you have the latest version of node.js and npm installed.
19943 error If you do, this is most likely a problem with the sqlite3 package,
19943 error not with npm itself.
19943 error Tell the author that this fails on your system:
19943 error     node-pre-gyp install --fallback-to-build
19943 error You can get information on how to open an issue for this project with:
19943 error     npm bugs sqlite3
19943 error Or if that isn't available, you can get their info via:
19943 error     npm owner ls sqlite3
19943 error There is likely additional logging output above.
19944 verbose exit [ 1, true ]
````

Still looking into the issue myself.

**Comment by McPo** [comment]
Was originally on node v6.2.1 had to downgrade to 5.11.1.
Then run "npm install".
It will fail, now move to the sqlite3 folder "cd ./node_modules/sqlite3"
Install nan, "npm install nan@~2.1.0"
Move back "cd -"
and try "npm install" again
It should succeed.

For my OSX machine the required commands where
````
brew unlink node
brew install node5
npm install # It will error out
cd ./node_modules/sqlite3
npm install nan@~2.1.0
cd -
npm install # Try again
````

**Comment by aguynamedben** [comment]
For what it's worth I'm also getting this same issue when using node v8.2.1, npm 5.3.0, and yarn 0.27.5. (I'm running `yarn` instead of `npm install`, but it fails at the same part with the same message).

**Comment by MattReimer** [comment]
Here's what worked for me (OSX + node v8.8.1):

I had sqlite3 already installed with homebrew.

In `package.json` change the version of sqlite3 (add a caret):

```
    "sqlite3": "^3.1.1"
```

Make sure `electron-rebuild` is installed `npm install electron-rebuild`

Then run `./node_modules/.bin/electron-rebuild -w sqlite3 -p`
